import { StyleSheet } from "react-native";
import {
  spacing,
  typography,
  radius,
  lineHeight,
  fontWeights,
  letterSpacings,
} from "@/constants/constants";

export const style = StyleSheet.create({
  container: {
    flex: 1,
    paddingHorizontal: spacing.lg,
    gap: 50,
    width: "100%",
  },
  scroll: {
    flex: 1,
    width: "100%",
  },
  scrollContent: {
    paddingBottom: spacing.xxl,
  },
  top: {
    marginTop: spacing.xl,
    display: "flex",
    alignItems: "center",
    width: "100%",
    flexDirection: "column",
    height: "auto",
    gap: 5,
  },
  topbar: {
    display: "flex",
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    width: "100%",
  },
  location: {
    textAlign: "center",
    fontSize: typography.h2,
    fontFamily: fontWeights.ExtraBold,
    letterSpacing: letterSpacings.h1,
    flex: 1,
  },
  date: {
    width: "auto",
    alignSelf: "center",
    paddingHorizontal: spacing.lg,
    paddingVertical: spacing.sm,
    borderRadius: radius.pill,
    fontSize: typography.body,
    fontFamily: fontWeights.Medium,
    letterSpacing: letterSpacings.tiny,
    margin: "auto",
  },
  weather: {
    textAlign: "center",
    alignSelf: "center",
    marginTop: 0,
    fontSize: typography.h2,
    fontFamily: fontWeights.SemiBold,
  },
  temp: {
    fontSize: typography.display,
    textAlign: "center",
    fontFamily: fontWeights.ExtraBold,
    letterSpacing: letterSpacings.display,
    lineHeight: lineHeight.display,
  },
  stats: {
    borderRadius: radius.md,
    width: "100%",
    height: 200,
    marginTop: spacing.xxl,
    display: "flex",
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-around",
  },
  summary: {
    fontSize: typography.cardTemp,
    fontFamily: fontWeights.Medium,
  },
  icon: {
    fontSize: 60,
  },
  statValue: {
    fontSize: typography.h2,
    fontFamily: fontWeights.SemiBold,
  },
  statProp: {
    fontSize: typography.body,
  },
  statBox: {
    alignItems: "center",
    gap: 2,
  },
  forecasts: {
    flexDirection: "row",
    gap: 20,
    height: 110,
  },
  forecast: {
    width: "100%",
    height: 280,
    marginTop: spacing.section,
    borderRadius: radius.md,
    padding: 15,
    gap:5
  },
  forecastHeader: {
    display: "flex",
    alignItems: "center",
    flexDirection: "row",
    gap: 5,
  },
  forecastHeadertext: {
    fontFamily: fontWeights.SemiBold,
    fontSize: typography.cardTemp,
  },
  forecastOptions: {
    height:30,
    borderRadius:30
  },
  searchField: {
    position: "absolute",
    top: 0,
    right: 0,
    bottom: 0,
    left: 0,
    zIndex: 100,
    paddingVertical: 100,
    paddingHorizontal: 20,
    display: "flex",
    justifyContent: "flex-start",
    alignItems: "center",
    gap: 10,
  },
  input: {
    width: "100%",
    maxWidth: 500,
    backgroundColor: "white",
    paddingHorizontal: 15,
    height: 50,
    zIndex: 100,
    position: "relative",
    borderRadius: radius.sm,
    fontFamily: fontWeights.SemiBold,
    fontSize: typography.body,
  },
  inputBlur: {
    width: 10000,
    position: "absolute",
    flex: 1,
    top: 0,
    right: 0,
    bottom: 0,
    left: 0,
    zIndex: 10,
  },
  city: {
    padding: 10,
    paddingVertical: 15,
    borderRadius: radius.xs,
    backgroundColor: "white",
  },
  cities: {
    width: "100%",
    maxWidth: 500,
    display: "flex",
    gap: 5,
    zIndex: 100,
  },
  image: {
    width: 40,
    height: 40,
  },
});
